INSERT INTO MANAGER_DTLS
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (111, 'ALEX', 'HENRY', 'SECURITY MANAGER', 52000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (112, 'JOHN', 'SMITH', 'HR MANAGER', 48000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (113, 'EMMA', 'WATSON', 'FINANCE MANAGER', 65000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (114, 'ROBERT', 'BROWN', 'OPERATIONS MANAGER', 60000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (115, 'MICHAEL', 'DAVIS', 'SECURITY MANAGER', 54000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (116, 'SOPHIA', 'MILLER', 'HR MANAGER', 47000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (117, 'DANIEL', 'WILSON', 'PROJECT MANAGER', 72000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (118, 'OLIVIA', 'MOORE', 'FINANCE MANAGER', 68000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (119, 'JAMES', 'TAYLOR', 'SECURITY MANAGER', 53000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (120, 'ISABELLA', 'ANDERSON', 'HR MANAGER', 49000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (121, 'WILLIAM', 'THOMAS', 'OPERATIONS MANAGER', 61000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (122, 'AVA', 'JACKSON', 'PROJECT MANAGER', 71000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (123, 'BENJAMIN', 'WHITE', 'SECURITY MANAGER', 55000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (124, 'MIA', 'HARRIS', 'HR MANAGER', 46500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (125, 'LUCAS', 'MARTIN', 'FINANCE MANAGER', 66000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (126, 'CHARLOTTE', 'THOMPSON', 'OPERATIONS MANAGER', 62000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (127, 'HENRY', 'GARCIA', 'SECURITY MANAGER', 52500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (128, 'AMELIA', 'MARTINEZ', 'PROJECT MANAGER', 73000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (129, 'ALEXANDER', 'ROBINSON', 'HR MANAGER', 48500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (130, 'EVELYN', 'CLARK', 'FINANCE MANAGER', 67000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (131, 'ETHAN', 'RODRIGUEZ', 'SECURITY MANAGER', 54500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (132, 'ABIGAIL', 'LEWIS', 'HR MANAGER', 47500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (133, 'MATTHEW', 'LEE', 'OPERATIONS MANAGER', 60500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (134, 'ELLA', 'WALKER', 'PROJECT MANAGER', 70000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (135, 'DAVID', 'HALL', 'SECURITY MANAGER', 56000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (136, 'SCARLETT', 'ALLEN', 'FINANCE MANAGER', 69000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (137, 'JOSEPH', 'YOUNG', 'HR MANAGER', 49500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (138, 'GRACE', 'KING', 'OPERATIONS MANAGER', 61500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (139, 'SAMUEL', 'WRIGHT', 'SECURITY MANAGER', 53500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (140, 'CHLOE', 'SCOTT', 'PROJECT MANAGER', 74000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (141, 'ANDREW', 'GREEN', 'HR MANAGER', 48000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (142, 'VICTORIA', 'ADAMS', 'FINANCE MANAGER', 67500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (143, 'RYAN', 'BAKER', 'SECURITY MANAGER', 55000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (144, 'LILY', 'NELSON', 'OPERATIONS MANAGER', 63000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (145, 'NATHAN', 'CARTER', 'HR MANAGER', 47000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (146, 'HANNAH', 'MITCHELL', 'PROJECT MANAGER', 72500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (147, 'CHRISTOPHER', 'PEREZ', 'SECURITY MANAGER', 56500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (148, 'ZOE', 'ROBERTS', 'FINANCE MANAGER', 68500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (149, 'JOSHUA', 'TURNER', 'HR MANAGER', 49000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (150, 'PENNY', 'PHILLIPS', 'OPERATIONS MANAGER', 64000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (151, 'ADAM', 'CAMPBELL', 'SECURITY MANAGER', 54500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (152, 'NORA', 'PARKER', 'PROJECT MANAGER', 73500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (153, 'JUSTIN', 'EVANS', 'HR MANAGER', 47500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (154, 'LEAH', 'EDWARDS', 'FINANCE MANAGER', 69500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (155, 'KEVIN', 'COLLINS', 'SECURITY MANAGER', 56000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (156, 'SARAH', 'STEWART', 'OPERATIONS MANAGER', 62500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (157, 'BRIAN', 'SANCHEZ', 'HR MANAGER', 48500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (158, 'JULIA', 'MORRIS', 'PROJECT MANAGER', 74500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (159, 'ERIC', 'ROGERS', 'SECURITY MANAGER', 57000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (160, 'KATE', 'REED', 'FINANCE MANAGER', 70500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (161, 'IAN', 'COOK', 'HR MANAGER', 49500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (162, 'MEGAN', 'MORGAN', 'OPERATIONS MANAGER', 63500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (163, 'SEAN', 'BELL', 'SECURITY MANAGER', 55500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (164, 'RACHEL', 'MURPHY', 'PROJECT MANAGER', 75000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (165, 'TOM', 'BAILEY', 'HR MANAGER', 48000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (166, 'LAURA', 'RIVERA', 'FINANCE MANAGER', 71000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (167, 'PETER', 'COOPER', 'SECURITY MANAGER', 56500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (168, 'MONICA', 'RICHARDSON', 'HR MANAGER', 50000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (169, 'MARK', 'HOWARD', 'OPERATIONS MANAGER', 65000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (170, 'ANNA', 'WARD', 'PROJECT MANAGER', 75500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (171, 'STEVE', 'BROOKS', 'SECURITY MANAGER', 57500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (172, 'DIANA', 'SANDERS', 'HR MANAGER', 50500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (173, 'PAUL', 'PRICE', 'FINANCE MANAGER', 72000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (174, 'KIM', 'BENNETT', 'OPERATIONS MANAGER', 65500);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (175, 'AARON', 'WOOD', 'SECURITY MANAGER', 58000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (176, 'EMILY', 'BARNES', 'PROJECT MANAGER', 76000);

INSERT INTO MANAGER_DTLS 
(MANAGER_ID, MANAGER_FIRSTNAME, MANAGER_LASTNAME, MANAGER_TYPE, MANAGER_SALARY)
VALUES (177, 'LUKE', 'ROSS', 'HR MANAGER', 51000);

